version: '3.8'
services:
  db:
    image: postgres
    container_name: inventory_db
    environment:
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: inventory
      POSTGRES_DB: inventory
  ports:
    - "5432:5432" 
  volumes:
    - ~/data:/var/lib/postgresql/data